[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/GameStartupMap.GameStartupMap
EditorStartupMap=/Game/Maps/GameStartupMap.GameStartupMap
+AdditionalMapsToCook=(MapPath="/Game/ThirdPerson/Maps/Lobby")
GlobalDefaultGameMode="/Script/MenuSystem.MenuSystemGameMode"
TransitionMap=/Game/Maps/TransitionMap.TransitionMap

[/Script/IOSRuntimeSettings.IOSRuntimeSettings]
MinimumiOSVersion=IOS_14

[/Script/Engine.RendererSettings]
r.Shadow.Virtual.Enable=1
r.Mobile.EnableNoPrecomputedLightingCSMShader=1


r.GenerateMeshDistanceFields=True

r.DynamicGlobalIlluminationMethod=1

r.ReflectionMethod=1

r.SkinCache.CompileShaders=True

r.RayTracing=True

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/Engine.Engine]
bSmoothFrameRate=False
bUseFixedFrameRate=False
+ActiveGameNameRedirects=(OldGameName="TP_ThirdPerson",NewGameName="/Script/MenuSystem")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_ThirdPerson",NewGameName="/Script/MenuSystem")
+ActiveClassRedirects=(OldClassName="TP_ThirdPersonGameMode",NewClassName="MenuSystemGameMode")
+ActiveClassRedirects=(OldClassName="TP_ThirdPersonCharacter",NewClassName="MenuSystemCharacter")

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=43CA1E2C489FA836E1E094A747953E91
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

; ===== Steam 配置（发布时取消注释） =====
;[/Script/Engine.GameEngine]
;!NetDriverDefinitions=ClearArray
;+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemSteam.SteamNetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

;[OnlineSubsystem]
;DefaultPlatformService=Steam
;PollingIntervalInMs=20
;bHasVoiceEnabled=true

;[OnlineSubsystemSteam]
;bEnabled=true
;SteamDevAppId=480
;bInitServerOnClient=true
;bAllowP2PPacketRelay=true
;bIsUsingP2PSockets=true

;[/Script/OnlineSubsystemSteam.SteamNetDriver]
;NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"

[/Script/Engine.GameUserSettings]
FullscreenMode=2
LastConfirmedFullscreenMode=2
ResolutionSizeX=1280
ResolutionSizeY=720

[OnlineSubsystem]
DefaultPlatformService=Null

[/Script/UnrealEd.CookerSettings]
bCookOnTheFlyForLaunchOn=False

[SystemSettings]
t.MaxFPS=60

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=60